title: Gradient Echo
pulseSeq:
  - t: 0
    FA: 90
    dur: 1
  - t: 2
    Gy: -1
    dur: 8
  - t: 12
    Gy: 1
    dur: 16
TR: 40
B0: 1.5
locations:
  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
speed: 0.003
background:
  color: white
output: 
  - type: 3D
    file: GRE_3D.mp4
    azimuth: 90
  - type: psd
    file: GRE_psd.mp4
  - type: xy
    file: GRE_xy.mp4
  - type: z
    file: GRE_z.mp4