title: Gradient Echo
pulseSeq:
  - t: 0
    FA: 90
    dur: 1
  - t: 1
    Gy: -3
    dur: 2
  - t: 3
    Gy: 0
    dur: 4
TR: 10
B0: 1.5
nIsochromats: 20
isochromatStep: 0.01
speed: 0.01
background:
  color: white
output: 
  - type: 3D
    file: GRE_3D.mp4
  - type: psd
    file: GRE_psd.mp4
  - type: xy
    file: GRE_xy.mp4
  - type: z
    file: GRE_z.mp4