title: Spatial Encoding
pulseSeq:
  - t: 0
    FA: 90
    dur: 1
  # - t: 1
  #   Gy: 1
  #   dur: 1
  # - t: 2
  #   Gx: -1
  #   dur: 2
  - t: 1
    Gx: 3
    dur: 5
TR: 7
B0: 0.5
# locations:
#   [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
locations:
  #[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
locSpacing: 0.0025
speed: 0.001
background:
  color: white
output:
  - type: 3D
    file: SpEnc_3D.mp4
    azimuth: 90
    #elevation: 30
  - type: psd
    file: SpEnc_psd.gif
  - type: kspace
    file: SpEnc_kspace.gif