title: Spoiled Gradient Echo
pulseSeq:
  - t: 0
    FA: 15
    dur: 0.5
  - t: 5
    spoil: true
TR: 5
nTR: 15
B0: 1.5
nIsochromats: 20
isochromatStep: 0.01
components:
  - T1: 60.0
    T2: 55.0
speed: 0.005
output:
  - type: 3D
    file: SPGR_3D.gif
  - type: kspace
    file: SPGR_kspace.gif
  - type: psd
    file: SPGR_psd.gif
  - type: xy
    file: SPGR_xy.gif
  - type: z
    file: SPGR_z.gif